import React from "react"
import Head from "next/head"
import CameraPicker from "./components/cameraPicker"
import useIntersectionStore from "./hooks/IntersectionStore"

//import { api } from "~/utils/api"

export default function Home() {
  const camera = useIntersectionStore((state) => state.camera)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen items-center justify-center">
          {camera === null && <CameraPicker />}
        </div>
      </main>
    </>
  )
}
