/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import React, { useState, useEffect } from 'react';
import Head from "next/head";
import Link from "next/link";
import Map from "~/pages/components/Map";
import CCTVImage from "~/pages/components/CCTVImage";

import { api } from "~/utils/api";

interface Data {
  location?: {
    coordinates?: number[];
  };
}

const camera = 326;
//const camera = 533;

function cctv_create_point(x: number, y: number) {
  console.log("cctv_create_point")
  console.log("x,y", x, y)
  return { x: x, y: y };
}

export default function Home() {

  const [data, setData] = useState<Data | null>(null);
  const [center, setCenter] = useState({ lat: 30.2672, lng: -97.7431 });
  const [coordinates, setCoordinates] = useState<Array<{ cctv: [number, number], map: [number, number] }>>([]);

  const addCoordinates = (cctvCoords: [number, number], mapCoords: [number, number]) => {
    setCoordinates(prevCoordinates => [...prevCoordinates, { cctv: cctvCoords, map: mapCoords }]);
  };

  useEffect(() => {
    console.log(data);
    if (data?.location?.coordinates) {
      const [lng, lat] = data.location.coordinates;
      if (lat && lng)
        setCenter({ lat, lng });
    }
  }, [data]);

  useEffect(() => {
    fetch('https://data.austintexas.gov/resource/b4k4-adkb.json?$where=camera_id=%22' + camera + '%22')
      .then(response => response.json())
      .then(data => setData(data[0]))
      .catch(error => console.error('Error:', error));
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', backgroundColor: '#333' }}>
        <CCTVImage cameraId={camera} coordinates={coordinates} createPoint={cctv_create_point} />
        <Map coordinates={coordinates} center={center} containerStyle={{ width: '50vw', height: '100vh' }} />
      </main>
    </>
  );
}
